{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cadquery as cq\n",
    "\n",
    "# Parameter definitions\n",
    "p_outerWidth = 100.0  # Outer width of box enclosure\n",
    "p_outerLength = 150.0  # Outer length of box enclosure\n",
    "p_outerHeight = 50.0  # Outer height of box enclosure\n",
    "\n",
    "p_thickness = 3.0  # Thickness of the box walls\n",
    "p_sideRadius = 10.0  # Radius for the curves around the sides of the bo\n",
    "p_topAndBottomRadius = 2.0  # Radius for the curves on the top and bottom edges\n",
    "\n",
    "p_screwpostInset = 12.0  # How far in from the edges the screwposts should be\n",
    "p_screwpostID = 4.0  # Inner diameter of the screwpost holes, should be roughly screw diameter not including threads\n",
    "p_screwpostOD = 10.0  # Outer diameter of the screwposts. Determines overall thickness of the posts\n",
    "\n",
    "p_boreDiameter = 8.0  # Diameter of the counterbore hole, if any\n",
    "p_boreDepth = 1.0  # Depth of the counterbore hole, if\n",
    "p_countersinkDiameter = 0.0  # Outer diameter of countersink. Should roughly match the outer diameter of the screw head\n",
    "p_countersinkAngle = 90.0  # Countersink angle (complete angle between opposite sides, not from center to one side)\n",
    "p_lipHeight = 1.0  # Height of lip on the underside of the lid. Sits inside the box body for a snug fit.\n",
    "\n",
    "# Outer shell\n",
    "oshell = cq.Workplane(\"XY\").rect(p_outerWidth, p_outerLength) \\\n",
    "                                 .extrude(p_outerHeight + p_lipHeight)\n",
    "\n",
    "# Weird geometry happens if we make the fillets in the wrong order\n",
    "if p_sideRadius > p_topAndBottomRadius:\n",
    "    oshell.edges(\"|Z\").fillet(p_sideRadius)\n",
    "    oshell.edges(\"#Z\").fillet(p_topAndBottomRadius)\n",
    "else:\n",
    "    oshell.edges(\"#Z\").fillet(p_topAndBottomRadius)\n",
    "    oshell.edges(\"|Z\").fillet(p_sideRadius)\n",
    "\n",
    "# Inner shell\n",
    "ishell = oshell.faces(\"<Z\").workplane(p_thickness, True)\\\n",
    "    .rect((p_outerWidth - 2.0 * p_thickness), (p_outerLength - 2.0 * p_thickness))\\\n",
    "    .extrude((p_outerHeight - 2.0 * p_thickness), False) # Set combine false to produce just the new boss\n",
    "ishell.edges(\"|Z\").fillet(p_sideRadius - p_thickness)\n",
    "\n",
    "# Make the box outer box\n",
    "box = oshell.cut(ishell)\n",
    "\n",
    "# Make the screwposts\n",
    "POSTWIDTH = (p_outerWidth - 2.0 * p_screwpostInset)\n",
    "POSTLENGTH = (p_outerLength - 2.0 * p_screwpostInset)\n",
    "\n",
    "postCenters = box.faces(\">Z\").workplane(-p_thickness)\\\n",
    "    .rect(POSTWIDTH, POSTLENGTH, forConstruction=True)\\\n",
    "    .vertices()\n",
    "\n",
    "for v in postCenters.all():\n",
    "    v.circle(p_screwpostOD / 2.0).circle(p_screwpostID / 2.0)\\\n",
    "     .extrude((-1.0) * ((p_outerHeight + p_lipHeight) - (2.0 * p_thickness)), True)\n",
    "\n",
    "# Split lid into top and bottom parts\n",
    "(lid, bottom) = box.faces(\">Z\").workplane(-p_thickness - p_lipHeight).split(keepTop=True, keepBottom=True).all()\n",
    "\n",
    "# Translate the lid, and subtract the bottom from it to produce the lid inset\n",
    "lowerLid = lid.translate((0, 0, -p_lipHeight))\n",
    "cutlip = lowerLid.cut(bottom).translate((p_outerWidth + p_thickness, 0, p_thickness - p_outerHeight + p_lipHeight))\n",
    "\n",
    "# Compute centers for counterbore/countersink or counterbore\n",
    "topOfLidCenters = cutlip.faces(\">Z\").workplane().rect(POSTWIDTH, POSTLENGTH, forConstruction=True).vertices()\n",
    "\n",
    "# Add holes of the desired type\n",
    "if p_boreDiameter > 0 and p_boreDepth > 0:\n",
    "    topOfLid = topOfLidCenters.cboreHole(p_screwpostID, p_boreDiameter, p_boreDepth, (2.0) * p_thickness)\n",
    "elif p_countersinkDiameter > 0 and p_countersinkAngle > 0:\n",
    "    topOfLid = topOfLidCenters.cskHole(p_screwpostID, p_countersinkDiameter, p_countersinkAngle, (2.0) * p_thickness)\n",
    "else:\n",
    "    topOfLid= topOfLidCenters.hole(p_screwpostID, 2.0 * p_thickness)\n",
    "\n",
    "# Return the combined result\n",
    "result = topOfLid.combineSolids(bottom)\n",
    "\n",
    "# Displays the result of this script\n",
    "show_object(result)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
