{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "4e07c71bb47344bfae4de4228bb086f7"
      }
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# 3d printer for mounting hotend to X-carriage inspired by the P3steel Toolson\n",
    "# edition - http://www.thingiverse.com/thing:1054909\n",
    "import cadquery as cq\n",
    "\n",
    "\n",
    "def move_to_center(cqObject, shape):\n",
    "    '''\n",
    "    Moves the origin of the current Workplane to the center of a given\n",
    "    geometry object\n",
    "    '''\n",
    "\n",
    "    # transform to workplane local coordinates\n",
    "    shape_center = shape.Center().sub(cqObject.plane.origin)\n",
    "\n",
    "    # project onto plane using dot product\n",
    "    x_offset = shape_center.dot(cqObject.plane.xDir)\n",
    "    y_offset = shape_center.dot(cqObject.plane.yDir)\n",
    "\n",
    "    return cqObject.center(x_offset, y_offset)\n",
    "\n",
    "# Parameter definitions\n",
    "\n",
    "main_plate_size_y = 67  # size of the main plate in y direction\n",
    "main_plate_size_x = 50.  # size of the main plate in x direction\n",
    "main_plate_thickness = 10.  # thickness of the main plate\n",
    "\n",
    "wing_size_x = 10.  # size of the side wing supporting the bridge in x direction\n",
    "wing_size_y = 10.  # size of the side wing supporting the bridge in y direction\n",
    "\n",
    "bridge_depth = 35.  # depth of the bridge\n",
    "\n",
    "support_depth = 18.  # depth of the bridge support\n",
    "\n",
    "cutout_depth = 15.  # depth of the hotend cutout\n",
    "cutout_rad = 8.     # radius of the cutout (cf groove mount sizes of E3D hotends)\n",
    "cutout_offset = 2.  # delta radius of the second cutout (cf groove mount sizes of E3D hotends)\n",
    "\n",
    "extruder_hole_spacing = 50.  # spacing of the extruder mounting holes (Wade's geared extruder)\n",
    "\n",
    "m4_predrill = 3.7  # hole diameter for m4 tapping\n",
    "m3_predrill = 2.5  # hole diameter for m3 tapping\n",
    "m3_cbore = 5.      # counterbore size for m3 socket screw\n",
    "\n",
    "mounting_hole_spacing = 28.  # spacing of the mounting holes for attaching to x-carriage\n",
    "\n",
    "aux_hole_depth = 6.    # depth of the auxiliary holes at the sides of the object\n",
    "aux_hole_spacing = 5.  # spacing of the auxiliary holes within a group\n",
    "aux_hole_N = 2         # number of the auxiliary hole per group\n",
    "\n",
    "# make the main plate\n",
    "res = cq.Workplane('front').box(main_plate_size_x,\n",
    "                                main_plate_size_y,\n",
    "                                main_plate_thickness)\n",
    "\n",
    "\n",
    "def add_wing(obj, sign=1):\n",
    "    '''\n",
    "    Adds a wing to the main plate, defined to keep the code DRY\n",
    "    '''\n",
    "    obj = obj.workplane()\\\n",
    "             .hLine(sign*wing_size_x)\\\n",
    "             .vLine(-wing_size_y)\\\n",
    "             .line(-sign*wing_size_x, -2*wing_size_y)\\\n",
    "             .close().extrude(main_plate_thickness)\n",
    "    return obj\n",
    "\n",
    "# add wings\n",
    "\n",
    "# add right wing\n",
    "res = res.faces('<Z').vertices('>XY')\n",
    "res = add_wing(res)\n",
    "\n",
    "# store sides of the plate for further reuse, their area is used later on to calculate \"optimum\" spacing of the aux hole groups\n",
    "face_right = res.faces('>X[1]').val()\n",
    "face_left = res.faces('>X[-2]').val()\n",
    "\n",
    "# add left wing\n",
    "res = res.faces('<Z').vertices('>Y').vertices('<X')\n",
    "res = add_wing(res, -1)\n",
    "\n",
    "# make the bridge for extruder mounting\n",
    "wp = res.faces('>Z')  # select top face\n",
    "e = wp.edges('>Y')    # select most extreme edge in Y direction\n",
    "\n",
    "bridge_length = e.val().Length()  # the width of the bridge equals to the length of the selected edge\n",
    "\n",
    "# draw the bridge x-section and extrude\n",
    "res = e.vertices('<X'). \\\n",
    "        workplane(). \\\n",
    "        hLine(bridge_length). \\\n",
    "        vLine(-10). \\\n",
    "        hLine(-bridge_length). \\\n",
    "        close().extrude(bridge_depth)\n",
    "\n",
    "faces = res.faces('>Z[1]')  # take all faces in Z direction and select the middle one; note the new selector syntax\n",
    "edge = faces.edges('>Y')    # select the top edge of this face...\n",
    "res = move_to_center(faces.workplane(), edge.val()).\\\n",
    "                     transformed(rotate=(0, 90, 0))  # ...and make a workplane that is centered in this edge and oriented along X direction\n",
    "\n",
    "res = res.vLine(-support_depth).\\\n",
    "    line(-support_depth, support_depth).\\\n",
    "    close()  # draw a triangle\n",
    "\n",
    "res = res.extrude(main_plate_size_x/2, both=True, clean=True)  # extrude the triangle, now the bridge has a nice support making it much more stiff\n",
    "\n",
    "# Start cutting out a slot for hotend mounting\n",
    "face = res.faces('>Y')  # select the most extreme face in Y direction, i.e. top ot the \"bridge\"\n",
    "res = move_to_center(face.workplane(), face.edges('>Z').val())  # shift the workplane to the center of the most extreme edge of the bridge\n",
    "\n",
    "\n",
    "def make_slot(obj, depth=None):\n",
    "    '''\n",
    "    Utility function that makes a slot for hotend mounting\n",
    "    '''\n",
    "    obj = obj.moveTo(cutout_rad, -cutout_depth).\\\n",
    "        threePointArc((0, -cutout_depth-cutout_rad),\n",
    "                      (-cutout_rad, -cutout_depth)).\\\n",
    "        vLineTo(0).hLineTo(cutout_rad).close()\n",
    "\n",
    "    if depth is None:\n",
    "        obj = obj.cutThruAll()\n",
    "    else:\n",
    "        obj = obj.cutBlind(depth)\n",
    "\n",
    "    return obj\n",
    "\n",
    "res = make_slot(res, None)  # make the smaller slot\n",
    "\n",
    "cutout_rad += cutout_offset  # increase the cutout radius...\n",
    "res = make_slot(res.end().end(), -main_plate_thickness/2)  # ...and make a slightly larger slot\n",
    "\n",
    "res = res.end().moveTo(0, 0) \\\n",
    "      .pushPoints([(-extruder_hole_spacing/2, -cutout_depth), (extruder_hole_spacing/2, -cutout_depth)]) \\\n",
    "      .hole(m4_predrill)  # add extruder mounting holes at the top of the bridge\n",
    "\n",
    "\n",
    "# make additional slot in the bridge support which allows the hotend's radiator to fit\n",
    "cutout_rad += 3*cutout_offset\n",
    "res = make_slot(res.end().moveTo(0, 0).workplane(offset=-main_plate_thickness))\n",
    "\n",
    "# add reinforcement holes\n",
    "cutout_rad -= 2*cutout_offset\n",
    "res = res.faces('>Z').workplane().\\\n",
    "          pushPoints([(-cutout_rad, -main_plate_thickness/4),\n",
    "                      (cutout_rad, -main_plate_thickness/4)]).\\\n",
    "          hole(m3_predrill)\n",
    "\n",
    "# add aux holes on the front face\n",
    "res = res.moveTo(-main_plate_size_x/2., 0).workplane().rarray(aux_hole_spacing, 1, aux_hole_N, 1) \\\n",
    "                                                      .hole(m3_predrill, depth=aux_hole_depth)\n",
    "res = res.moveTo(main_plate_size_x, 0).workplane().rarray(aux_hole_spacing, 1, aux_hole_N, 1) \\\n",
    "                                                  .hole(m3_predrill, depth=aux_hole_depth)\n",
    "\n",
    "# make a hexagonal cutout\n",
    "res = res.faces('>Z[1]')\n",
    "res = res.workplane(offset=bridge_depth). \\\n",
    "      transformed(rotate=(0, 0, 90)). \\\n",
    "      polygon(6, 30).cutThruAll()\n",
    "\n",
    "# make 4 mounting holes with cbores\n",
    "res = res.end().moveTo(0, 0). \\\n",
    "      rect(mounting_hole_spacing,\n",
    "           mounting_hole_spacing, forConstruction=True)\n",
    "\n",
    "res = res.vertices(). \\\n",
    "          cboreHole(m3_predrill,\n",
    "                    m3_cbore,\n",
    "                    bridge_depth+m3_cbore/2)\n",
    "\n",
    "# make cutout and holes for mounting of the fan\n",
    "res = res.transformed(rotate=(0, 0, 45)). \\\n",
    "      rect(35, 35).cutBlind(-bridge_depth).end(). \\\n",
    "      rect(25, 25, forConstruction=True).vertices().hole(m3_predrill)\n",
    "\n",
    "\n",
    "def make_aux_holes(workplane, holes_span, N_hole_groups=3):\n",
    "    '''\n",
    "    Utility function for creation of auxiliary mouting holes at the sides of the object\n",
    "    '''\n",
    "    res = workplane.moveTo(-holes_span/2).workplane().rarray(aux_hole_spacing, 1, aux_hole_N, 1) \\\n",
    "                                                     .hole(m3_predrill, depth=aux_hole_depth)\n",
    "    for i in range(N_hole_groups-1):\n",
    "        res = res.moveTo(holes_span/(N_hole_groups-1.)).workplane().rarray(aux_hole_spacing, 1, aux_hole_N, 1) \\\n",
    "                                                                     .hole(m3_predrill, depth=aux_hole_depth)\n",
    "\n",
    "    return res\n",
    "\n",
    "# make aux holes at the bottom\n",
    "res = res.faces('<Y').workplane()\n",
    "res = make_aux_holes(res, main_plate_size_x*2/3., 3)\n",
    "\n",
    "# make aux holes at the side (@overhang)\n",
    "res = res.faces('<X').workplane().transformed((90, 0, 0))\n",
    "res = make_aux_holes(res, main_plate_size_x*2/3., 3)\n",
    "res = res.faces('>X').workplane().transformed((90, 0, 0))\n",
    "res = make_aux_holes(res, main_plate_size_x*2/3., 3)\n",
    "\n",
    "# make aux holes at the side (@main plate)\n",
    "res = res.faces('|X').edges('<Y').edges('>X')\n",
    "res = res.workplane()\n",
    "res = move_to_center(res, face_right)\n",
    "res = res.transformed((90, 0, 0))\n",
    "hole_sep = 0.5*face_right.Area()/main_plate_thickness\n",
    "res = make_aux_holes(res, hole_sep, 2)\n",
    "\n",
    "# make aux holes at the side (@main plate)\n",
    "res = res.faces('|X').edges('<Y').edges('<X')\n",
    "res = res.workplane()\n",
    "res = move_to_center(res, face_left)\n",
    "res = res.transformed((0, 180, 0))\n",
    "hole_sep = 0.5*face_right.Area()/main_plate_thickness\n",
    "res = make_aux_holes(res, hole_sep, 2)\n",
    "\n",
    "# show the result\n",
    "show_object(res)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
